### PR TITLE
feat: add option auth-http for gitlab/github provider, fix #344

### LINKED ISSUE #344: Add an option to use https protocol with personal access token instead of ssh
Hello again :)

Allow to clone with https url and personal access token, see:
- https://kettan007.medium.com/how-to-clone-a-git-repository-using-personal-access-token-a-step-by-step-guide-ab7b54d4ef83

I will make a MR.

### PR DESCRIPTION
**Pull request by jagu-sayan**
Hello @orf,

I manually tested this solution with Gitlab and Github for all commands.

I also upgrade all dependencies, I didn't find any breaking change.
If you are not comfortable with this, I can make this change in another pull request/commit.

Thanks for your awesome project !

### CODE REVIEW

**Comment by orf** [comment]
Hey @jagu-sayan - thank you so much for this! I'm currently travelling for work so my time is constrained, but after a quick glance this looks amazing!

I'll try it myself this evening and cut a release. Thank you so much ❤️

**Comment by orf** [comment]
Also, straight up fantastic idea: I didn't even consider pulling directly with the tokens, but it's a great feature

**Comment by jagu-sayan** [comment]
In fact, I don't give my credentials to git-workspace (exept the token used to query Gitlab/Github API). When I do a first clone, git ask my username and password (token) that is stored with git credential helper.
On following git clone, I have nothing to do, git automatically find my credentials.

```bash
# Check if you have a credential helper configured
❯ git config --get credential.helper

# First time:
❯ git clone https://github.com/jagu-sayan/array.git
Cloning into 'array'...
Username for 'https://github.com': jagu-sayan
Password for 'https://jagu-sayan@github.com': PUT_MY_GITLAB_OR_GITHUB_TOKEN
remote: Enumerating objects: 16, done.
remote: Total 16 (delta 0), reused 0 (delta 0), pack-reused 16
Receiving objects: 100% (16/16), done.
Resolving deltas: 100% (6/6), done.

# Now I can use git-workspace
❯ export GITHUB_TOKEN=TOKEN_USED_FOR_GRAPHQL_API
❯  git-workspace add github unix-thrust --auth-http
Adding Github user/org unix-thrust in directory github, using the token stored in GITHUB_TOKEN to ...
❯   git workspace update
```

So, this can be improve, because it's failling if my credentials are not stored.

**Comment by jagu-sayan** [comment]
Hello @orf,

Can I help you to test this feature ? Or maybe something block you ?
If so, don't hesitate to chat with me https://matrix.to/#/#jagu-sayan:gitter.im.

I can help to implement unit test and #135 and #329 features.

I have also some other ideas to improve this clients:
- Add an option to allow `run` subcommand to see output of the running command for each repository
- Add a way to select a subest of repositories for `run` subcommand

Please, tell me if you are interesting by some features (or all) ?

**Comment by orf** [comment]
Hey! Apologies, I’ve been a bit busy. I’ve given it a test and merged, thank you again!

I’ve cut a new release as well. As for the other issues, I’m happy to take a look at any contributions for them! They are not something I personally need right now, but they fit nicely and happy to have them added.

**Pull request merged**
