### PR TITLE
Add support to include repositories

### LINKED ISSUE #171: Allow specifying individual repos
While it is very useful to manage all repos in an org together, most of my orgs have too many repos, including many I am not interested in.

It would be nice if individual repos can be supported.

### PR DESCRIPTION
**Pull request by magiconair**
This patch adds support to both add include and exclude expressions to filter repositories. The repository names are first run through the include and then exclude filters. By default all repositories are included.

Fixes #171

### CODE REVIEW

**Comment by magiconair** [comment]
This is my first `rust` code so please bear with me. I could also use some help updating the tests since I don't know how to run them.

**Comment by orf** [comment]
Hey @magiconair! Thanks for the contribution - it looks perfect!

I'm currently on a train and won't be able to merge this until I get back on Sunday. I also need to get the CI set up to run on pull requests!

Thanks again, and not bad for some first rust code! Certainly better than my first rust code 😫

**Review by mikkelens — APPROVED** [review]
This addition seems fine to me. The only bits I would personally change are style-related. Can we get this merged?

**Comment by orf** [comment]
Sorry for the very late reply here @magiconair - this slipped off my radar. I've rebased the PR here https://github.com/orf/git-workspace/pull/359 and I'll merge it in a moment.

Thanks for your contribution ❤️

**Pull request closed without merging**
